#undef ADD
#undef  OR
#undef CMP
#undef SBB
#undef SUB
#undef LEA
#undef MOV
#undef     F
#undef    MRM
#undef        Z
#undef        B
#undef        W
#undef        R
#undef          AX
#undef          CX
#undef          DX
#undef          BX
#undef          SP
#undef          BP
#undef          SI
#undef          DI
#undef            BX_SI
#undef            BX_DI
#undef            BP_SI
#undef            BP_DI
#undef            SI_
#undef            DI_
#undef            BP_
#undef            BX_
#undef TEST
#undef IMUL
#undef INC_
#undef DEC_
#undef JMP_
#undef POP
#undef PUSH
#undef ADDAX
#undef LODS
#undef LAHF
#undef NOT
#undef JZ
#undef HALT
#undef INT
#undef MOVAXI
#undef CALL
